// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubluxqnoghecfpukaaxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVibHV4cW5vZ2hlY2ZwdWthYXhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNTk4MzUsImV4cCI6MjA2OTYzNTgzNX0.7_yrSReQpWl1ncfxIMO8C7bBsKolzjf6JPVQ4lM5Cdo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});